In [2]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2 = np.array([1,2,3,4, "naitik"])
print(arr2, type(arr2) ,arr2.shape)

arr3 = np.array([ [1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(arr3, arr3.shape)

arr3 = np.full((3, 4), 100)
print(arr3, arr3.shape)

print(arr3, arr3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' 'naitik'] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [11]:

arr1 = np.array((2, 3), dtype="int64")
print(arr1, arr1.shape)

arr2 = np.ones((5,))
print(arr2, arr2.shape)

arr3 = np.full((3, 4), 100)
print(arr3, arr3.shape)

arr4 = np.eye(3, 3)
print(arr4, arr4.shape)


arr5 = np.arange(4,11,4)
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4)
print(arr6, arr6.shape)

[2 3] (2,)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[4 8] (2,)
[  1.  34.  67. 100.] (4,)


In [12]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [13]:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr, arr.shape)

reshape = arr.reshape(3, 2)
print(reshape, reshape.shape)

flat = arr.flatten()
print(flat, flat.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [14]:
arr=np.array([1,2,3,4,5,6])
print(arr,arr.dtype)

[1 2 3 4 5 6] int64


In [15]:
# complex no
arr=np.array([3+5j])
print(arr , arr.dtype)


[3.+5.j] complex128


In [16]:

arr = np.array(["prime", 1, 2, 3, 4])
print(arr, arr.dtype)


['prime' '1' '2' '3' '4'] <U21


In [26]:


arr2D = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2D)

# Sum of all elements
print(np.sum(arr2D))

# Sum of each column
sum_of_column = np.sum(arr2D, axis=0)
print(sum_of_column)

# Sum of each row
sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [28]:
# vectorisation
arr=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
print(arr ** 2)
print(arr+arr2)



[ 1  4  9 16 25]
[ 2  4  6  8 10]


In [3]:
# brodcasting
arr=np.array([1,2,3,4,5])
print(arr+5)

[ 6  7  8  9 10]


In [1]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean) / std_dev
print(normalized_arr)
print(mean)
print(std_dev)
print(np.sqrt(std_dev))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.057371263440564
